name: Manual trigger

run-name: Deploy ${{ inputs.application }}/${{ inputs.branch }} to ${{ inputs.environment }}-${{ inputs.region}}
permissions:
  contents: read
on:
  workflow_dispatch:
    inputs:
      action:
        type: choice
        description: 'Action'
        required: true
        default: 'CHOOSE THE ACTION'
        options:
          - 'CHOOSE THE ACTION'
          - action1
          - action2
          - action3
          - set schedule
      application:
        type: choice
        description: 'Application'
        required: true
        default: 'CHOOSE THE APP'
        options:
          - 'CHOOSE THE APP'
          - app1
          - app2
          - app3
      option1:
        type: string
        default: '1'
        description: 'option 1'
        required: false
      option2:
        type: string
        default: '2'
        description: 'option 2'
        required: false
      boolean1:
        default: 'true'
        required: true
      boolean2:
        default: true
        required: true

jobs:
  what_i_do:
    runs-on: ubuntu-latest
    # outputs:
    steps:
      - uses: actions/checkout@v3
      - id: message
        run: echo "TEST=$(<test.txt)" >> $GITHUB_ENV
      - name: Print Input Values
        id: debug
        run: |
          echo "send_maint_notification input is: ${{ github.event.inputs.boolean1 }}"
          echo "send_maint_notification input is: ${{ github.event.inputs.boolean1 }}"


      - id: test_env_var
        run: echo $TEST
      - id: test
        run: echo ${{ inputs.option2 }}
      - id: debug_pwd
        run: pwd
      - id: debug_ls
        run: ls -l

    
