on:
  push:

jobs:
  call_test_action:
    name: call test action
    uses: ./.github/workflows/test-action.yml
    with:
        environment: dev
        VAR_TEST: ${{ vars.VAR_TEST}}
    secrets:
        TEST: ${{ secrets.TEST}}
