name: test action

env:
  USE_REMOTE_CACHE: true
  PUBLISH_IMAGE: false

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment name, should be dev, qa, or prod'
        type: string
        required: true
      VARTEST:
        type: string
      bool1:
        default: true
      bool2:
        default: true
    secrets:
      TEST:
        required: true

        

jobs:
  test:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:

      - name: echo hidden secret
        run: echo secret ${{ secrets.TEST}}

      - name: echo var
        run: echo var ${{ vars.VARTEST }}

      - name: Print Input Values
        run: |
          echo "send_maint_notification input is: ${{ github.event.inputs.bool1 }}"
          echo "send_maint_notification input is: ${{ github.event.inputs.bool2 }}"

